import React from 'react';
import {Img, useCurrentFrame, useVideoConfig} from 'remotion';
import {resolveLayerState} from '@editorial-motion/motion-engine';
import type {MotionEvent} from '@editorial-motion/motion-schema';

export type SceneLayerPlacement = {
  x: number;
  y: number;
  width: number;
  height: number;
  anchorX?: number;
  anchorY?: number;
  zIndex: number;
};

export type SceneLayerProps = {
  asset: string;
  placement: SceneLayerPlacement;
  events: readonly MotionEvent[];
};

/** Generic deterministic layer renderer. Scene-specific React is never generated by the planner. */
export const SceneLayer: React.FC<SceneLayerProps> = ({asset, placement, events}) => {
  const frame = useCurrentFrame();
  const {fps, width, height} = useVideoConfig();
  const state = resolveLayerState(frame, fps, events);
  const anchorX = placement.anchorX ?? 0.5;
  const anchorY = placement.anchorY ?? 0.5;
  const hidden = (1 - state.revealProgress) * 100;
  let clipPath: string | undefined;
  if (state.clip?.kind === 'mask') {
    clipPath = `circle(${(state.revealProgress * 75).toFixed(2)}% at 50% 50%)`;
  } else if (state.clip?.kind === 'wipe') {
    const direction = state.clip.direction;
    if (direction === 'right') clipPath = `inset(0 0 0 ${hidden}%)`;
    else if (direction === 'up') clipPath = `inset(0 0 ${hidden}% 0)`;
    else if (direction === 'down') clipPath = `inset(${hidden}% 0 0 0)`;
    else clipPath = `inset(0 ${hidden}% 0 0)`;
  } else if (state.revealProgress < 1) {
    clipPath = `inset(0 ${hidden}% 0 0)`; // legado: reveal sem clip declarado
  }

  return (
    <Img
      src={asset}
      style={{
        position: 'absolute',
        left: placement.x * width,
        top: placement.y * height,
        width: placement.width * width,
        height: placement.height * height,
        zIndex: placement.zIndex,
        opacity: state.opacity,
        objectFit: 'fill',
        transformOrigin: `${anchorX * 100}% ${anchorY * 100}%`,
        transform: `translate(${state.translateX * width}px, ${state.translateY * height}px) scale(${state.scale})`,
        clipPath,
      }}
    />
  );
};
